name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */8 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@3.21
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Seoul
          plugin_languages: yes
          #plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS"      # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage, lines       # Additionally display total bytes size and percentage
          plugin_languages_threshold: 0%                                # Hides all languages less than 2%
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_indepth: yes                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 1000                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 91                               # Limit recently used stats to last week
          commits_authoring: kua@kakao.com        # Surnames or email addresses used to identify your commits
