name: Example
uses: lowlighter/metrics@latest
with:
  filename: metrics.classic.svg
  config_timezone: Asia/Seoul
  token: ${{ secrets.METRICS_TOKEN }}
  base: header, repositories
  plugin_lines: yes
